services:
  - type: web
    name: check-wa
    env: node
    buildCommand: ./render-build.sh
    startCommand: node server.js
    plan: free
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
